variable "environment" {}
variable "location" {}
variable "workspace" {}
variable "kubernetes_version" {}
variable "system_pool_node_count" {}
variable "worker_pool_node_count" {}
variable "vm_sku_system_pool" {}
variable "vm_sku_worker_pool" {}
variable "os_sku" {}
variable "use_availability_zones" {}
variable "max_pods" {}
variable "os_disk_size_gb" {}
