# Checkov pipeline.
# Scans the Terraform code.
# Skipped Checks.
# CKV_AZURE_6 - Ensure AKS has an API Server Authorised IP Ranges enabled

resources:
  repositories:
    - repository: Azure.Terraform
      type: github
      endpoint: busadave13
      name: busadave13/Azure.Terraform

trigger: none

pr:
  branches:
    include:
      - dev
      - stage
      - prod

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
  - checkout: Azure.Terraform
  - script: |
      echo "Running Checkov Scan!"
      sudo apt-get install software-properties-common
      sudo add-apt-repository ppa:deadsnakes/ppa
      sudo apt install python3-pip
      sudo apt-get install python3-testresources
      sudo python3.7 -m pip install botocore==1.20.112
      sudo python3.7 -m pip install -U checkov
      checkov -d Azure.Terraform/infrastructure --framework terraform --external-checks-dir Azure.Terraform/infrastructure --skip-check CKV_AZURE_6
    displayName: "Terraform code scan using Checkov"
