location                           = "westus"
environment                        = "staging"
workspace                          = "network"
address_space                      = "10.0.0.0/15"
system_subnet_address_space        = "10.0.0.0/18"
worker_subnet_address_space        = "10.0.64.0/18"
container_app_subnet_address_space = "10.0.128.0/18"
